using Day1;
using Day2;
using Day3;
using Day4;
using Day5;
using Day6;
using Day7;
using Day8;
using Day9;
using Day10;
using Day11;
using Day12;
using Day13;

//CalorieCounting.StartDay1();
//RockPaperScissorsGame.StartDay2();
//RucksackRecognition.StartDay3();
//CampCleanup.StartDay4();
//SupplyStacks.StartDay5();
//TuningTrouble.StartDay6();
//NoSpaceLeftOnDevice.StartDay7();
//TreetopTreeHouse.StartDay8();
//RopeBridge.StartDay9();
//CathodeRayTube.StartDay10();
//MonkeyInTheMiddle.StartDay11();
//HillClimbingAlgorithm.StartDay12();
DistressSignal.StartDay13();
//Day13.Other.Solve();

Console.ReadLine();